openapi: 3.0.0
info:
  title: Gest√£o Avarias
  description: Dispatching
  contact:
    name: a037264
    email: a037264@ismai.pt
  version: 0.0.1
servers:
- url: http://localhost:8080
  description: Meu localhost
  variables:
    basePath:
      default: /
paths:
  /avarias:
    get:
      tags:
      - AvariasController
      summary: Retrieve Avarias
      operationId: retrieveAvarias
      responses:
        "200":
          description: Array of Avarias model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Avaria'
                x-content-type: application/json
      x-swagger-router-controller: AvariasController
    post:
      tags:
      - AvariasController
      summary: Create Avaria
      operationId: createAvaria
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Avaria'
      responses:
        "200":
          description: Create a Avaria model instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Avaria'
      x-swagger-router-controller: AvariasController
  /avarias/{id}:
    get:
      tags:
      - AvariasController
      summary: Retrieve Avaria
      operationId: retrieveAvaria
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrieve Avaria id 1
            value: 1
          two:
            summary: Retrieve Avaria id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Avaria'
        "400":
          description: Bad request
        "404":
          description: Id not found
      x-swagger-router-controller: AvariasController
    put:
      tags:
      - AvariasController
      summary: Update Avaria
      operationId: updateAvaria
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Avaria id 1
            value: 1
          two:
            summary: Update Avaria id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Avaria'
            examples:
              AvariaExemplo01:
                $ref: '#/components/examples/AvariaExemplo01'
              AvariaExemplo02:
                $ref: '#/components/examples/AvariaExemplo02'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Avarias PUT success
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: Id not found
      x-swagger-router-controller: AvariasController
    delete:
      tags:
      - AvariasController
      summary: Delete Avaria
      operationId: deleteAvaria
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Avarias id 1
            value: 1
          two:
            summary: Delete Avarias id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: Id not found
      x-swagger-router-controller: AvariasController
  /antenas:
    get:
      tags:
      - AntenasController
      summary: Retrieve Antenas
      operationId: retrieveAntenas
      parameters:
      - name: nome
        in: query
        description: Array filter by name of Antena
        required: false
        style: form
        explode: true
        schema:
          type: string
        examples:
          one:
            summary: Antenas com a palavra 'Espinho' no nome
            value: Espinho
      responses:
        "200":
          description: Array of Antenas model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Antena'
                x-content-type: application/json
      x-swagger-router-controller: AntenasController
    post:
      tags:
      - AntenasController
      summary: Create Antena
      operationId: createAntena
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Antena'
      responses:
        "200":
          description: Create a Antena model instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Antena'
      x-swagger-router-controller: AntenasController
  /antenas/{id}:
    get:
      tags:
      - AntenasController
      summary: Retrieve Antena
      operationId: retrieveAntena
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrieve Antena id 1
            value: 1
          two:
            summary: Retrieve Antena id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Antena'
        "400":
          description: Bad request
        "404":
          description: Id not found
      x-swagger-router-controller: AntenasController
    put:
      tags:
      - AntenasController
      summary: Update Antena
      operationId: updateAntena
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Antenas id 1
            value: 1
          two:
            summary: Update Antenas id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Antena'
            examples:
              AntenaExemplo01:
                $ref: '#/components/examples/AntenaExemplo01'
              AntenaExemplo02:
                $ref: '#/components/examples/AntenaExemplo02'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Antenas PUT success
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: Id not found
      x-swagger-router-controller: AntenasController
    delete:
      tags:
      - AntenasController
      summary: Delete Antena
      operationId: deleteAntena
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Antenas id 1
            value: 1
          two:
            summary: Delete Antenas id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: Id not found
      x-swagger-router-controller: AntenasController
  /utilizadores:
    get:
      tags:
      - UtilizadoresController
      summary: Retrieve Utilizadores
      operationId: retrieveUtilizadores
      parameters:
      - name: cargo
        in: query
        description: Array filter by cargo of Utilizador
        required: false
        style: form
        explode: true
        schema:
          type: string
        examples:
          one:
            summary: Utilizadores com cargo de Admin
            value: Admin
          two:
            summary: Utilizadores com cargo de Gestor
            value: Gestor
          three:
            summary: Utilizadores com cargo de Tecnico
            value: Tecnico
      responses:
        "200":
          description: Array of Utilizadores model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utilizador'
                x-content-type: application/json
      x-swagger-router-controller: UtilizadoresController
    post:
      tags:
      - UtilizadoresController
      summary: Create Utilizador
      operationId: createUtilizador
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilizador'
      responses:
        "200":
          description: Create a Utilizador model instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
      x-swagger-router-controller: UtilizadoresController
  /utilizadores/{id}:
    get:
      tags:
      - UtilizadoresController
      summary: Retrieve Utilizador
      operationId: retrieveUtilizador
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Retrieve Utilizador id 1
            value: 1
          two:
            summary: Retrieve Utilizador id 2
            value: 2
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
        "400":
          description: Bad request
        "404":
          description: Id not found
      x-swagger-router-controller: UtilizadoresController
    put:
      tags:
      - UtilizadoresController
      summary: Update Utilizador
      operationId: updateUtilizador
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Update Utilizadores id 1
            value: 1
          two:
            summary: Update Utilizadores id 2
            value: 2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilizador'
            examples:
              AntenaExemplo01:
                $ref: '#/components/examples/UtilizadorExemplo01'
              AntenaExemplo02:
                $ref: '#/components/examples/UtilizadorExemplo02'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                description: Utilizadores PUT success
                x-content-type: application/json
        "400":
          description: Bad request
        "404":
          description: Id not found
      x-swagger-router-controller: UtilizadoresController
    delete:
      tags:
      - UtilizadoresController
      summary: Delete Utilizador
      operationId: deleteUtilizador
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Utilizadores id 1
            value: 1
          two:
            summary: Delete Utilizadores id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: Id not found
      x-swagger-router-controller: UtilizadoresController
  /antenas_favoritas/{id_utilizador}:
    get:
      tags:
      - AntenasFavoritasController
      summary: Retrieve Antenas Favoritas
      operationId: retrieveAntenasFavoritas
      parameters:
      - name: id_utilizador
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Antenas Favoritas do id_utilizador 1
            value: 1
          two:
            summary: Antenas Favoritas do id_utilizador 2
            value: 2
      responses:
        "200":
          description: Array of Antenas Favoritas model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AntenaFavorita'
                x-content-type: application/json
      x-swagger-router-controller: AntenasFavoritasController
  /antenas_favoritas/{id_utilizador}/{id_antena}:
    post:
      tags:
      - AntenasFavoritasController
      summary: Create Antena Favorita
      operationId: createAntenaFavorita
      parameters:
      - name: id_utilizador
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Create Antena Favorita id_utilizador 1
            value: 1
          two:
            summary: Create Antena Favorita id_utilizador 2
            value: 2
      - name: id_antena
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Create Antena Favorita id_antena 1
            value: 1
          two:
            summary: Create Antena Favorita id_antena 2
            value: 2
      responses:
        "200":
          description: Create a Antena Favorita model instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AntenaFavorita'
      x-swagger-router-controller: AntenasFavoritasController
    delete:
      tags:
      - AntenasFavoritasController
      summary: Delete Antena Favorita
      operationId: deleteAntenaFavorita
      parameters:
      - name: id_utilizador
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Antena Favorita id_utilizador 1
            value: 1
          two:
            summary: Delete Antena Favorita id_utilizador 2
            value: 2
      - name: id_antena
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Antena Favorita id_antena 1
            value: 1
          two:
            summary: Delete Antena Favorita id_antena 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: Id not found
      x-swagger-router-controller: AntenasFavoritasController
  /comentarios:
    post:
      tags:
      - ComentariosController
      summary: Create Comentario
      operationId: createComentario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comentario'
      responses:
        "200":
          description: Create a Comentario model instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comentario'
      x-swagger-router-controller: ComentariosController
  /comentarios/{id}:
    get:
      tags:
      - ComentariosController
      summary: Retrieve Comentarios
      operationId: retrieveComentarios
      parameters:
      - name: type
        in: query
        description: Array filter by name of Antena
        required: true
        style: form
        explode: true
        schema:
          type: string
        examples:
          por_utilizador:
            summary: Buscar coment√°rios de um utilizador
            value: utilizador
          por_antena:
            summary: Buscar coment√°rios de uma antena
            value: antena
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Buscar comentarios do id 1
            value: 1
          two:
            summary: Buscar comentarios do id 2
            value: 2
      responses:
        "200":
          description: Array of Comentarios model instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comentario'
                x-content-type: application/json
      x-swagger-router-controller: ComentariosController
    delete:
      tags:
      - ComentariosController
      summary: Delete Comentario
      operationId: deleteComentario
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 1
          type: integer
          format: int64
        examples:
          one:
            summary: Delete Comentario id 1
            value: 1
          two:
            summary: Delete Comentario id 2
            value: 2
      responses:
        "204":
          description: No Content
        "404":
          description: Id not found
      x-swagger-router-controller: ComentariosController
components:
  schemas:
    Avaria:
      title: Avaria
      required:
      - id_antena
      - id_utilizador
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        id_utilizador:
          type: integer
          format: int64
        id_antena:
          type: integer
          format: int64
        status:
          type: integer
          format: int32
        data_abertura:
          type: integer
          format: int64
        data_conclusao:
          type: integer
          format: int64
        detalhe:
          type: string
      example:
        nome: Antena Espinho
        id_utilizador: 2
        id_antena: 12
        detalhe: Sem sinal
    Antena:
      title: Antena
      required:
      - latitude
      - longitude
      - nome
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        latitude:
          type: number
        longitude:
          type: number
      example:
        nome: Antena Espinho
        latitude: 41.007336
        longitude: -8.63365
    AntenaFavorita:
      title: Antena Favorita
      required:
      - id_antena
      - id_utilizador
      type: object
      properties:
        id_utilizador:
          type: integer
          format: int64
        id_antena:
          type: integer
          format: int64
      example:
        id_antena: 6
        id_utilizador: 2
    Comentario:
      title: Comentario
      required:
      - conteudo
      - id_antena
      - id_utilizador
      type: object
      properties:
        id:
          type: integer
          format: int64
        id_utilizador:
          type: integer
          format: int64
        id_antena:
          type: integer
          format: int64
        conteudo:
          type: string
        data_criacao:
          type: integer
          format: int64
      example:
        id_utilizador: 1
        id_antena: 3
        conteudo: Antena sem baterias
    Utilizador:
      title: Utilizador
      required:
      - cargo
      - email
      - nome
      - password
      - telefone
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        email:
          type: string
        cargo:
          type: string
        telefone:
          type: string
        password:
          type: string
      example:
        nome: Lucas
        cargo: Admin
        email: lucas@gmail.com
        telefone: "919999999"
        password: Admin123
  examples:
    AvariaExemplo01:
      value:
        nome: Antena Espinho
        id_utilizador: 1
        id_antena: 12
        detalhe: SITE DOWN
    AvariaExemplo02:
      value:
        nome: Antena Braga
        id_utilizador: 2
        id_antena: 14
        detalhe: ""
    AntenaExemplo01:
      value:
        nome: Antena Espinho
        latitude: 41.007336
        longitude: -8.63365
    AntenaExemplo02:
      value:
        nome: Antena Braga
        latitude: 41.552277
        longitude: -8.424503
    AntenaFavoritaExemplo01:
      value:
        id_antena: 2
        id_utilizador: 6
    AntenaFavoritaExemplo02:
      value:
        id_antena: 1
        id_utilizador: 8
    ComentarioExemplo01:
      value:
        id_utilizador: 1
        id_antena: 5
        conteudo: Antena sem energia
    ComentarioExemplo02:
      value:
        id_utilizador: 1
        id_antena: 3
        conteudo: Sem Luz
    UtilizadorExemplo01:
      value:
        nome: Sergio
        email: sergio@ismai.pt
        cargo: tecnico
        telefone: "919999998"
        password: Tecnico123
    UtilizadorExemplo02:
      value:
        nome: Tiago
        email: tiago@ismai.pt
        cargo: gestor
        telefone: "919999998"
        password: Gestor123
